### PR TITLE
login page set up done

### PR DESCRIPTION
**Pull request by michaelujkim**

### CODE REVIEW

**Review by siddharthparmar7 — CHANGES_REQUESTED** [review]
Good work Mike!

Please remove comments from your files and propType imports if you are not using them.

Please use external styles.js, no inline styling.

Thank you!

**Comment by michaelujkim** [comment]
Requested changes made to commit, thanks

**Review by siddharthparmar7 — CHANGES_REQUESTED** [review]
Login.js remove the import for propTypes if you are not using it. This component should be a stateless component.

LoginContainer.js -> remove propType import if you are not using it.

**Comment by michaelujkim** [comment]
Login component is stateless, all unused imports deleted, all unused comments deleted

**Review by siddharthparmar7 — APPROVED** [review]
Thank you!

**Pull request merged**
