### PR TITLE
added eslint

### PR DESCRIPTION
**Pull request by michaelujkim**
also created assets/image files with splash screen

### CODE REVIEW

**Review by siddharthparmar7 — CHANGES_REQUESTED** [review]
Good work Mike!

I see that you also added the splash screen. Please add another dependency to your pull request saying you are adding the splash screen image.

Thank you!

**Comment by michaelujkim** [comment]
hi dependencies are updated

**Review by siddharthparmar7 — CHANGES_REQUESTED** [review]
your dependency says "splash screen CSS." I don't see any CSS in your commit. You have added just an image not code, so keep that in mind while creating a dependency for it.

Your branch has conflicts. Please resolve them.

Please fix this. Thank you!

**Comment by michaelujkim** [comment]
hi,
conflict resolved, and new issue dependency created to accurately portray the task completed

**Review by siddharthparmar7 — CHANGES_REQUESTED** [review]
Thank you for making Changes Mike. Please make sure that you squash commits. I can see 8 commits here.

Thank you!

**Comment by mandiwise** [comment]
Closing and redo-ing this!

**Pull request closed without merging**
